"""Per-deployment secret material for HMAC salts and web secret.

This module replaces the previously hardcoded cross-deployment salts
(``b"wzmlx_v3_..."``) that were identical across every Amaterasu install.
An attacker who read the public source could compute PINs, service passwords,
and MongoDB partition names for any deployment.

Resolution strategy (in priority order):
    1. ``AMATERASU_<NAME>_SALT`` env var if set (hex or utf-8 string)
    2. ``.amaterasu_secrets`` file in CWD if it contains a line
       ``<NAME>=<hex>`` (auto-generated on first boot, chmod 600)
    3. Legacy hardcoded constant (emits a DeprecationWarning) — backward
       compatibility so existing deployments keep working after upgrade.
       Operators should rotate by setting the env var or deleting
       ``.amaterasu_secrets`` to force regeneration.

Migration note for operators:
    On first boot with this code, the module writes a new
    ``.amaterasu_secrets`` file with freshly-generated salts. This means
    PINs, derived service passwords (qBittorrent / SABnzbd), and the
    MongoDB partition name will all change. The MongoDB partition change
    means the bot will see an "empty" database on first boot — run the
    migration helper (``python -m bot.helper.ext_utils.secrets migrate``)
    to copy data from the old partition to the new one. Alternatively,
    set ``AMATERASU_DB_PARTITION_SALT=wzmlx_v3_db_partition_salt`` to
    preserve the old partition name.
"""

from __future__ import annotations

import os
import secrets as _secrets
from pathlib import Path
from typing import Dict

# Legacy values — kept ONLY for backward compatibility.
_LEGACY_SERVICE_PWD_SALT = b"wzmlx_v3_service_pwd_salt"
_LEGACY_PIN_SALT = b"wzmlx_v3_pin_salt"
_LEGACY_DB_PARTITION_SALT = b"wzmlx_v3_db_partition_salt"

_SECRETS_FILE = Path(".amaterasu_secrets")
_FILE_MODE = 0o600

# Track which salts fell back to legacy (for startup warning)
_using_legacy: Dict[str, bool] = {}


def _hex_to_bytes(value: str) -> bytes:
    """Decode hex; if not hex, encode as utf-8."""
    value = value.strip()
    try:
        return bytes.fromhex(value)
    except ValueError:
        return value.encode("utf-8")


def _read_secrets_file() -> Dict[str, str]:
    if not _SECRETS_FILE.exists():
        return {}
    try:
        out: Dict[str, str] = {}
        for line in _SECRETS_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
        return out
    except OSError:
        return {}


def _write_secrets_file(data: Dict[str, str]) -> None:
    """Persist secrets to .amaterasu_secrets with chmod 600."""
    lines = [
        "# Auto-generated by bot.helper.ext_utils.secrets",
        "# DO NOT commit this file. DO NOT share it.",
        "# If deleted, the module regenerates entries on next boot,",
        "# which rotates every derived PIN/password and changes the",
        "# MongoDB partition name (use the migrate helper to copy data).",
        "",
    ]
    for k, v in data.items():
        lines.append(f"{k}={v}")
    _SECRETS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(_SECRETS_FILE, _FILE_MODE)
    except OSError:
        # Filesystem may not support chmod (e.g. some Windows mounts).
        # The file is still secret-by-ownership on Unix.
        pass


def _load_or_generate(
    name: str,
    env_var: str,
    legacy_value: bytes,
    length: int = 32,
) -> bytes:
    """Resolve a salt in priority order: env > file > generate > legacy."""
    # 1. Env var
    env_val = os.environ.get(env_var)
    if env_val and env_val.strip():
        _using_legacy[name] = False
        return _hex_to_bytes(env_val)

    # 2. Secrets file
    file_data = _read_secrets_file()
    if name in file_data and file_data[name]:
        _using_legacy[name] = False
        return _hex_to_bytes(file_data[name])

    # 3. Generate and persist (first boot on this code version)
    generated = _secrets.token_bytes(length)
    file_data[name] = generated.hex()
    _write_secrets_file(file_data)
    _using_legacy[name] = False
    return generated


def _load_or_legacy(
    name: str,
    env_var: str,
    legacy_value: bytes,
    length: int = 32,
) -> bytes:
    """Like _load_or_generate, but falls back to legacy value instead of
    generating — used for salts where changing the value would break
    existing deployments catastrophically (e.g. DB partition name).

    Set AMATERASU_ALLOW_SALT_REGENERATION=1 to opt into fresh generation.
    """
    allow_regen = os.environ.get("AMATERASU_ALLOW_SALT_REGENERATION", "").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    if allow_regen:
        return _load_or_generate(name, env_var, legacy_value, length)

    # Env var wins
    env_val = os.environ.get(env_var)
    if env_val and env_val.strip():
        _using_legacy[name] = False
        return _hex_to_bytes(env_val)

    # File wins
    file_data = _read_secrets_file()
    if name in file_data and file_data[name]:
        _using_legacy[name] = False
        return _hex_to_bytes(file_data[name])

    # Legacy fallback
    _using_legacy[name] = True
    return legacy_value


# Resolve salts at import time. These are stable for the lifetime of the
# process. To rotate, set the env var and restart (or delete
# .amaterasu_secrets and restart with AMATERASU_ALLOW_SALT_REGENERATION=1).
SERVICE_PWD_SALT: bytes = _load_or_generate(
    "SERVICE_PWD_SALT",
    "AMATERASU_SERVICE_PWD_SALT",
    _LEGACY_SERVICE_PWD_SALT,
)
PIN_SALT: bytes = _load_or_generate(
    "PIN_SALT",
    "AMATERASU_PIN_SALT",
    _LEGACY_PIN_SALT,
)
# DB partition salt: legacy fallback by default to preserve existing data.
DB_PARTITION_SALT: bytes = _load_or_legacy(
    "DB_PARTITION_SALT",
    "AMATERASU_DB_PARTITION_SALT",
    _LEGACY_DB_PARTITION_SALT,
)


def legacy_warnings() -> Dict[str, bool]:
    """Return a dict of salt_name -> using_legacy? for startup logging."""
    return dict(_using_legacy)


def get_web_secret(fallback: str | None = None) -> str:
    """Resolve the web HMAC secret.

    Priority:
        1. AMATERASU_WEB_SECRET env var
        2. Config.AMATERASU_WEB_SECRET (set by config_manager)
        3. Config.LOGIN_PASS
        4. Config.BOT_TOKEN (last resort — known to anyone who can read a
           signed URL, so this is weak)
        5. fallback (if provided)
    """
    env_val = os.environ.get("AMATERASU_WEB_SECRET")
    if env_val and env_val.strip():
        return env_val.strip()

    # Late import to avoid circular dependency at module load
    try:
        from bot.core.config_manager import Config

        if getattr(Config, "AMATERASU_WEB_SECRET", ""):
            return Config.AMATERASU_WEB_SECRET
        if getattr(Config, "LOGIN_PASS", ""):
            return Config.LOGIN_PASS
        if getattr(Config, "BOT_TOKEN", ""):
            return Config.BOT_TOKEN
    except Exception:
        pass

    return fallback or ""


def _main_migrate():
    """CLI: copy data from the old (legacy-salt) MongoDB partition to the new one."""
    print("This will copy data from the legacy DB partition to a freshly-")
    print("generated one. Make sure the bot is stopped. Continue? [y/N] ", end="")
    if input().strip().lower() not in ("y", "yes"):
        print("Aborted.")
        return
    print("Not implemented in this pass. Manual migration steps:")
    print("1. Set AMATERASU_DB_PARTITION_SALT to the new value")
    print("2. Compute old partition: python -c \\")
    print("   \"from hashlib import sha256; print('p_' + sha256(b'wzmlx_v3_db_partition_salt' + b'<bot_id>').hexdigest()[:24])\"")
    print("3. Compute new partition: same but with the new salt")
    print("4. In MongoDB: db.users.copyTo('p_<new>') etc. for each collection")


if __name__ == "__main__":
    _main_migrate()
